<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-19T15:07:29 EET" name="Default suite" finished-at="2021-06-19T15:07:34 EET" duration-ms="5209">
    <groups>
    </groups>
    <test started-at="2021-06-19T15:07:29 EET" name="Default test" finished-at="2021-06-19T15:07:34 EET" duration-ms="5209">
      <class name="Restassured_test">
        <test-method is-config="true" signature="GetURL()[pri:0, instance:Restassured_test@429bffaa]" started-at="2021-06-19T15:07:29 EET" name="GetURL" finished-at="2021-06-19T15:07:30 EET" duration-ms="1041" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetURL -->
        <test-method signature="NegativeTest()[pri:0, instance:Restassured_test@429bffaa]" started-at="2021-06-19T15:07:30 EET" name="NegativeTest" finished-at="2021-06-19T15:07:33 EET" duration-ms="2910" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Meghan_Littel@rene.us> but was:<null>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Meghan_Littel@rene.us> but was:<null>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at Restassured_test.NegativeTest(Restassured_test.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeTest -->
        <test-method signature="getRestassuredRequest()[pri:1, instance:Restassured_test@429bffaa]" started-at="2021-06-19T15:07:33 EET" name="getRestassuredRequest" finished-at="2021-06-19T15:07:33 EET" duration-ms="420" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getRestassuredRequest -->
        <test-method signature="getRequestQP()[pri:2, instance:Restassured_test@429bffaa]" started-at="2021-06-19T15:07:33 EET" name="getRequestQP" finished-at="2021-06-19T15:07:34 EET" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getRequestQP -->
        <test-method signature="postRequest()[pri:3, instance:Restassured_test@429bffaa]" started-at="2021-06-19T15:07:34 EET" name="postRequest" finished-at="2021-06-19T15:07:34 EET" duration-ms="491" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postRequest -->
      </class> <!-- Restassured_test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
